# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            SKills to Career with Interests and Values Ontology
url:               https://nehakeshan.github.io/
baseurl:          https://nehakeshan.github.io/test/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://nehakeshan.github.io/test/